#! /usr/bin/env python2.7

from gaupy.log import LOGFile
from gaupy.molecules import SuperMolecule
from gaupy.filenames import GaussianFile
import sys
import argparse

parser = argparse.ArgumentParser('Split a multimolecular Gaussian output file'
                                 ' or XYZ file into unimolecular XYZ files.')
parser.add_argument('files', nargs='*', help='Multimolecular Gaussian output'
                    ' or xyz files', default=sys.stdin)
args = parser.parse_args()


for f in args.files:
    try:
        try:
            molecule = SuperMolecule.from_xyz(f)
            name = GaussianFile(f)
        except:
            molecule = LOGFile(f)
            name = molecule.files
        for i, m in enumerate(molecule.geometry.molecules()):
            m.to_xyz(name.add(i).xyz)
    except:
        print('ERROR: %s could not be processed' % f)
