#! /usr/bin/env python2.7

from gaupy.log import LOGFile
from gaupy.molecules import SuperMolecule
from gaupy.filenames import GaussianFile
import sys
import argparse

parser = argparse.ArgumentParser('Split a multimolecular Gaussian output file'
                                 ' or XYZ file into unimolecular XYZ files.')
parser.add_argument('--scaling', '-s',
                    help='Scaling factor for bond recognition (default=1.0)',
                    default=1.0, type=float)
parser.add_argument('files', nargs='*', help='Multimolecular Gaussian output'
                    ' or xyz files', default=sys.stdin)
args = parser.parse_args()


for f in args.files:
    try:
        try:
            molecule = SuperMolecule.from_xyz(f)
            name = GaussianFile(f)
        except:
            logfile = LOGFile(f)
            molecule = logfile.geometry
            name = logfile.files
        molecule.scaling = args.scaling
        for i, m in enumerate(molecule.molecules()):
            m.to_xyz(name.add(i+1).xyz)
    except:
        print('ERROR: %s could not be processed' % f)
