#! /usr/bin/env python2.7

import sys
import gaupy.log as log
import argparse

parser = argparse.ArgumentParser('Write IRC, scan or optimization movie.')
parser.add_argument('files', nargs='*', help='Gaussian output files',
                    default=sys.stdin)
args = parser.parse_args()

for f in args.files:
    l = log.LOGFile(f)
    fnmovie = l.files.add('movie').xyz
    fmovie = open(fnmovie, 'w')
    fmovie.write(l.movie())
    fmovie.close()
    print('%s written.' % fnmovie)
