#! /usr/bin/python

import argparse
import sys
import gaupy.log as log

parser = argparse.ArgumentParser('Create a input file that will restart'
                                 + ' a Gaussian calculation.')
parser.add_argument('files', nargs='*', help='Gaussian output files',
                    default=sys.stdin)
args = parser.parse_args()

for f in args.files:
    logf = log.LOGFile(f)
    restart = logf.to_input()
    open(logf.files.com, 'w').write(restart)
    print('%s written.' % logf.files.com)
