#! /usr/bin/env python2.7

import gaupy.log as log
import argparse
import sys

parser = argparse.ArgumentParser('Supporting information summary.')
parser.add_argument('files', nargs='*', help='Gaussian output files',
                    default=sys.stdin)
args = parser.parse_args()

try:
    files = args.files.read().split()
except:
    files = args.files

for f in args.files:
    print
    print(f)
    l = log.LOGFile(f)
    print(l.geometry.to_string(width=17))
    print('Electronic energy (M06-2X/6-31+G(d,p), Ha): %16.7f' % l.energy)
    print('Gibbs free energy correction (298K, 1 atm, Ha): %12.7f'
          % l.gibbscorrection)
    print('Lowest vibrational frequency (cm-1): %23.4f' % l.lowest_frequency)
print
